### ISSUE TITLE
process.exit is not a function

### ISSUE THREAD

**Issue by nokome** [stencila/logga#68]
The `defaultHandler` function will, by default, exit on errors if in Node.js (you can turn this off or define your own handler):

https://github.com/stencila/logga/blob/7174736cabe01707eb0efc18636a0ae064ea564f/index.ts#L329-L337

But we have been seeing the error `process.exit is not a function` in browser based deployments of Logga where the assumption is that `typeof process === 'undefined'`.

@alex-ketch Is there a better way to check for this? Should we just add `&& process.exit !== undefined` or use `process?.exit !== undefined`

**Comment by alex-ketch** [comment]
After digging around a bit, seems the above logic isn't at fault.
ParcelJS adds [`node-libs-browser`](https://www.npmjs.com/package/node-libs-browser) shim to the compiled project, which partially populates a `process` object in the browser (see screenshot).
It doesn't include the `exit` method, hence the failure.

I _think_ the below change to use [optional calls](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) should be enough to safeguard against this.

```diff
   const { exitOnError = true } = options 
   if ( 
     typeof process !== 'undefined' && 
     exitOnError && 
     level === LogLevel.error 
   ) { 
-     process.exit(1) 
+    process.exit?.(1) 
   } 
 } 
```

**Comment by nokome** [comment]
Closed in https://github.com/stencila/logga/commit/9cf7e6e76b40e7cecb672134fdfb69fc9308c8f8
