### ISSUE TITLE
Make runable in the browser

### ISSUE THREAD

**Issue by nokome** [stencila/logga#8]
The tagline for this project is:

> 🌲 Emit log events from anywhere. Consistently.

We've developed it in the context of Node.js and use `process` as the global event bus (to which events get emitted and listeners get added). But I was always envisaged that we _should_ be able to use the same approach in the browser but instead of using logging to console, have a handler that creates a toast or similar.

Over in `executa`, I recently added some `log.info` and `log.warn` calls [inside `Executor.discover`](https://github.com/stencila/executa/blob/dca380d18b7817ba4a1a4c5c524a67a670b7a877/src/base/Executor.ts#L524-L543). Earlier today, we discussed having some sort of event emitting to display this kind of info to the user. So, given that the `Executor` class is designed to run in both the browser and in Node.js, I wondered if it is now time to generalize `logga` so that it can run in the browser as well.

I don't think this would be too difficult to do. Requires having switches for browser equivalents for `process.addListener(LOG_EVENT_NAME, handler)` etc. Related: https://pineco.de/creating-a-javascript-event-bus/

What do you think @beneboy and @alex-ketch ?

**Comment by beneboy** [comment]
Couldn't we just have a check in logga that was like

```javascript
if (window.loggaHandler !== undefined) {
loggaHandler(level, message);
}
```

Then if you want to handle logs on a page just implement that function. Simple and quick to implement.

**Comment by alex-ketch** [comment]
I think creating an abstraction over `process.emit` and `window.dispatchEvent` would be my suggested route and wouldn't bee too difficult.

Though right now I'm not sure it's a pressing need, as most of the important events will be coming through Manager or some other intermediary service, and I think we should have less developer focused messaging on the UI.
